### ISSUE TITLE
Improve mat images - consistent size and host

### ISSUE THREAD

**Issue by avidmeher** [scythe-discord/scythe-bidder#40]
The images are hosted on geekdo, arstechnica and steam, and are of different sizes (from 826 x 325 to 5669 x 2319) and UI formats. Also, the image for the [Mechanical](https://steamuserimages-a.akamaihd.net/ugc/968727454197258419/AC405A3EB987C0F804E6D439C7B738E5F3546272/) mat is different.

1. Create new images with consistent size. Ensure coin and popularity numbers are clear.
2. Consider hosting images on the same host. Image host suggestions needed.

This will help with #15 too.

**Comment by avidmeher** [comment]
I prefer an image like this (screen grab from DE) over an actual image of the mat.
![image](https://user-images.githubusercontent.com/72496368/95738495-f46fbc80-0ca6-11eb-9280-5d78368908e0.png)

**Comment by rezende** [comment]
+1 to DE images, I have all the full screenshots, they need to be cropped:

Engineering: https://steamcommunity.com/sharedfiles/filedetails/?id=2119161229
Industrial: https://steamcommunity.com/sharedfiles/filedetails/?id=2119161524
Patriotic: https://steamcommunity.com/sharedfiles/filedetails/?id=2119161000
Mehcanical: https://steamcommunity.com/sharedfiles/filedetails/?id=2119160710
Agricultural: https://steamcommunity.com/sharedfiles/filedetails/?id=2119160458
Militant: https://steamcommunity.com/sharedfiles/filedetails/?id=2119160110

**Comment by Rusty-Shackleford** [comment]
I've created high quality versions of all the DE mats.  Here is an [example of all the mats in a single image](https://steamuserimages-a.akamaihd.net/ugc/1731045024488654308/0B8E05EAF925323D52BBB16F56AD9752136283FE/).  If interested, I can provide these - I have each mat as an individual PSD file.

**Comment by avidmeher** [comment]
Should have closed this issue when I updated the mats.
> 
> 
> I've created high quality versions of all the DE mats. Here is an [example of all the mats in a single image](https://steamuserimages-a.akamaihd.net/ugc/1731045024488654308/0B8E05EAF925323D52BBB16F56AD9752136283FE/). If interested, I can provide these - I have each mat as an individual PSD file.

@Rusty-Shackleford : the website already uses the same images that you linked.
