### ISSUE TITLE
Adding toggle for low tier and high tier combinations similar to the IFA toggle

### ISSUE THREAD

**Issue by nrsimonelli** [scythe-discord/scythe-bidder#49]
Would like to add two additional toggle options which change the pool of combinations available. These should function alongside the IFA toggle where only one option may be selected at a time. If no toggles are selected the game should proceed with base mode combinations and player size as normal.

**Comment by lightyearsaway** [comment]
This should be included in #39 , yeah? Although your proposal on #36 could maybe reduce the need for something like this?
